/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB977Xjfple3X9rNcKZ9YGjCEGr0IvKQ08',
    appId: '1:336304310664:web:0cf3737052d90bf54d923d',
    messagingSenderId: '336304310664',
    projectId: 'hid-image-96250',
    authDomain: 'hid-image-96250.firebaseapp.com',
    storageBucket: 'hid-image-96250.firebasestorage.app',
    measurementId: 'G-FEYZBJ0WCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSpa_S3if0w_Vs1Ak7e2n_riwwekC7u8k',
    appId: '1:336304310664:android:0a5d100f78944a824d923d',
    messagingSenderId: '336304310664',
    projectId: 'hid-image-96250',
    storageBucket: 'hid-image-96250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9hX0LysGB3dmZhSciCiexitQ-CECF4Aw',
    appId: '1:336304310664:ios:6baa063368786fbd4d923d',
    messagingSenderId: '336304310664',
    projectId: 'hid-image-96250',
    storageBucket: 'hid-image-96250.firebasestorage.app',
    iosBundleId: 'com.example.hidImageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9hX0LysGB3dmZhSciCiexitQ-CECF4Aw',
    appId: '1:336304310664:ios:6baa063368786fbd4d923d',
    messagingSenderId: '336304310664',
    projectId: 'hid-image-96250',
    storageBucket: 'hid-image-96250.firebasestorage.app',
    iosBundleId: 'com.example.hidImageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB977Xjfple3X9rNcKZ9YGjCEGr0IvKQ08',
    appId: '1:336304310664:web:cd91e421ce60d6884d923d',
    messagingSenderId: '336304310664',
    projectId: 'hid-image-96250',
    authDomain: 'hid-image-96250.firebaseapp.com',
    storageBucket: 'hid-image-96250.firebasestorage.app',
    measurementId: 'G-V37QH4GKN3',
  );
}
*/
